/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.text.MaskFormatter;

/**
 *
 * @author wcarlosg
 */
public class ConfirmaCompraPrazoView extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmaCompraPrazoView
     */
    MaskFormatter dataAPagar;
    
    public ConfirmaCompraPrazoView() {
        initComponents();
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpVencido = new javax.swing.ButtonGroup();
        grpPago = new javax.swing.ButtonGroup();
        jPanelPrincipal = new javax.swing.JPanel();
        lbAPagar = new javax.swing.JLabel();
        lbVencimento = new javax.swing.JLabel();
        tfAPagar = new javax.swing.JFormattedTextField();
        tfVencimento = new javax.swing.JFormattedTextField();
        jPanelVencido = new javax.swing.JPanel();
        lbVencido = new javax.swing.JLabel();
        rbVencidoSim = new javax.swing.JRadioButton();
        rbVencidoNao = new javax.swing.JRadioButton();
        jPanelVencido1 = new javax.swing.JPanel();
        lbPago = new javax.swing.JLabel();
        rbPagoSim = new javax.swing.JRadioButton();
        rbPagoNao1 = new javax.swing.JRadioButton();
        lbIcone = new javax.swing.JLabel();
        jPanelDescricao = new javax.swing.JPanel();
        lbFuncionario = new javax.swing.JLabel();
        lbFornecedor = new javax.swing.JLabel();
        lbValorFinal = new javax.swing.JLabel();
        lbFornecedor1 = new javax.swing.JLabel();
        lbFuncionario1 = new javax.swing.JLabel();
        lbValorFinal1 = new javax.swing.JLabel();
        jbConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirmações de compras");
        setAlwaysOnTop(true);

        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbAPagar.setText("A pagar:");

        lbVencimento.setText("Vencimento:");

        try {
            tfAPagar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAPagarActionPerformed(evt);
            }
        });

        try {
            tfVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfVencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVencimentoActionPerformed(evt);
            }
        });

        jPanelVencido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelVencido.setPreferredSize(new java.awt.Dimension(190, 38));

        lbVencido.setText("Vencido:");

        grpVencido.add(rbVencidoSim);
        rbVencidoSim.setText("Sim");
        rbVencidoSim.setMaximumSize(new java.awt.Dimension(54, 22));
        rbVencidoSim.setMinimumSize(new java.awt.Dimension(54, 22));
        rbVencidoSim.setPreferredSize(new java.awt.Dimension(54, 22));
        rbVencidoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVencidoSimActionPerformed(evt);
            }
        });

        grpVencido.add(rbVencidoNao);
        rbVencidoNao.setText("Não");
        rbVencidoNao.setMaximumSize(new java.awt.Dimension(54, 22));
        rbVencidoNao.setMinimumSize(new java.awt.Dimension(54, 22));
        rbVencidoNao.setPreferredSize(new java.awt.Dimension(54, 22));
        rbVencidoNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVencidoNaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVencidoLayout = new javax.swing.GroupLayout(jPanelVencido);
        jPanelVencido.setLayout(jPanelVencidoLayout);
        jPanelVencidoLayout.setHorizontalGroup(
            jPanelVencidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVencidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbVencido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbVencidoSim, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbVencidoNao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelVencidoLayout.setVerticalGroup(
            jPanelVencidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVencidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVencidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVencido)
                    .addComponent(rbVencidoSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbVencidoNao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelVencido1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelVencido1.setPreferredSize(new java.awt.Dimension(190, 38));

        lbPago.setText("Pago:");

        grpPago.add(rbPagoSim);
        rbPagoSim.setText("Sim");
        rbPagoSim.setPreferredSize(new java.awt.Dimension(54, 22));
        rbPagoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPagoSimActionPerformed(evt);
            }
        });

        grpPago.add(rbPagoNao1);
        rbPagoNao1.setText("Não");
        rbPagoNao1.setPreferredSize(new java.awt.Dimension(54, 22));
        rbPagoNao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPagoNao1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVencido1Layout = new javax.swing.GroupLayout(jPanelVencido1);
        jPanelVencido1.setLayout(jPanelVencido1Layout);
        jPanelVencido1Layout.setHorizontalGroup(
            jPanelVencido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVencido1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbPagoSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbPagoNao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanelVencido1Layout.setVerticalGroup(
            jPanelVencido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVencido1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVencido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPago)
                    .addComponent(rbPagoSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbPagoNao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pagar.png"))); // NOI18N

        jPanelDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lbFuncionario.setText("Funcionário:");

        lbFornecedor.setText("Fornecedor:");

        lbValorFinal.setText("Valor total:");

        lbFornecedor1.setText("null");

        lbFuncionario1.setText("null:");

        lbValorFinal1.setText("null");

        javax.swing.GroupLayout jPanelDescricaoLayout = new javax.swing.GroupLayout(jPanelDescricao);
        jPanelDescricao.setLayout(jPanelDescricaoLayout);
        jPanelDescricaoLayout.setHorizontalGroup(
            jPanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescricaoLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFornecedor)
                    .addComponent(lbValorFinal)
                    .addComponent(lbFuncionario))
                .addGap(18, 18, 18)
                .addGroup(jPanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFornecedor1)
                    .addComponent(lbValorFinal1)
                    .addComponent(lbFuncionario1))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanelDescricaoLayout.setVerticalGroup(
            jPanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDescricaoLayout.createSequentialGroup()
                        .addComponent(lbFornecedor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbFuncionario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbValorFinal1))
                    .addGroup(jPanelDescricaoLayout.createSequentialGroup()
                        .addComponent(lbFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbValorFinal)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jPanelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 95, Short.MAX_VALUE))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfVencimento)
                            .addComponent(tfAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbIcone)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelVencido1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(jPanelVencido, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanelVencido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelVencido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbAPagar)
                                .addComponent(tfAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbVencimento)
                                .addComponent(tfVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lbIcone)))
                .addGap(18, 18, 18)
                .addComponent(jPanelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jbConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Confirmar.png"))); // NOI18N
        jbConfirmar.setText("CONFIRMAR");
        jbConfirmar.setPreferredSize(new java.awt.Dimension(132, 40));
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void tfAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAPagarActionPerformed

    private void tfVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVencimentoActionPerformed

    private void rbVencidoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVencidoSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbVencidoSimActionPerformed

    private void rbVencidoNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVencidoNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbVencidoNaoActionPerformed

    private void rbPagoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPagoSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPagoSimActionPerformed

    private void rbPagoNao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPagoNao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPagoNao1ActionPerformed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbConfirmarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grpPago;
    private javax.swing.ButtonGroup grpVencido;
    private javax.swing.JPanel jPanelDescricao;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelVencido;
    private javax.swing.JPanel jPanelVencido1;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JLabel lbAPagar;
    private javax.swing.JLabel lbFornecedor;
    private javax.swing.JLabel lbFornecedor1;
    private javax.swing.JLabel lbFuncionario;
    private javax.swing.JLabel lbFuncionario1;
    private javax.swing.JLabel lbIcone;
    private javax.swing.JLabel lbPago;
    private javax.swing.JLabel lbValorFinal;
    private javax.swing.JLabel lbValorFinal1;
    private javax.swing.JLabel lbVencido;
    private javax.swing.JLabel lbVencimento;
    private javax.swing.JRadioButton rbPagoNao1;
    private javax.swing.JRadioButton rbPagoSim;
    private javax.swing.JRadioButton rbVencidoNao;
    private javax.swing.JRadioButton rbVencidoSim;
    private javax.swing.JFormattedTextField tfAPagar;
    private javax.swing.JFormattedTextField tfVencimento;
    // End of variables declaration//GEN-END:variables
}


