/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.text.MaskFormatter;

/**
 *
 * @author wcarlosg
 */
public class ConfirmaVendaPrazoView extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmaCompraPrazoView
     */
    MaskFormatter dataAPagar;
    
    public ConfirmaVendaPrazoView() {
        initComponents();
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpVencido = new javax.swing.ButtonGroup();
        grpPago = new javax.swing.ButtonGroup();
        jPanelPrincipal = new javax.swing.JPanel();
        lbAReceber = new javax.swing.JLabel();
        lbVencimento = new javax.swing.JLabel();
        tfAReceber = new javax.swing.JFormattedTextField();
        tfVencimento = new javax.swing.JFormattedTextField();
        jPanelVenceu = new javax.swing.JPanel();
        lbVenceu = new javax.swing.JLabel();
        rbVenceuSim = new javax.swing.JRadioButton();
        rbVenceuNao = new javax.swing.JRadioButton();
        jPanelPago = new javax.swing.JPanel();
        lbPago = new javax.swing.JLabel();
        rbPagoSim = new javax.swing.JRadioButton();
        rbPagoNao = new javax.swing.JRadioButton();
        lbIcone = new javax.swing.JLabel();
        jPanelDescricao = new javax.swing.JPanel();
        lbFuncionario = new javax.swing.JLabel();
        lbCliente = new javax.swing.JLabel();
        lbValorFinal = new javax.swing.JLabel();
        lbFornecedor1 = new javax.swing.JLabel();
        lbFuncionario1 = new javax.swing.JLabel();
        lbValorFinal1 = new javax.swing.JLabel();
        jbConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Confirmações de vendas");
        setAlwaysOnTop(true);

        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbAReceber.setText("A receber:");

        lbVencimento.setText("Vencimento:");

        try {
            tfAReceber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfAReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAReceberActionPerformed(evt);
            }
        });

        try {
            tfVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfVencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVencimentoActionPerformed(evt);
            }
        });

        jPanelVenceu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelVenceu.setPreferredSize(new java.awt.Dimension(190, 40));

        lbVenceu.setText("Venceu:");

        grpVencido.add(rbVenceuSim);
        rbVenceuSim.setText("Sim");
        rbVenceuSim.setMaximumSize(new java.awt.Dimension(54, 22));
        rbVenceuSim.setMinimumSize(new java.awt.Dimension(54, 22));
        rbVenceuSim.setPreferredSize(new java.awt.Dimension(54, 22));
        rbVenceuSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVenceuSimActionPerformed(evt);
            }
        });

        grpVencido.add(rbVenceuNao);
        rbVenceuNao.setText("Não");
        rbVenceuNao.setMaximumSize(new java.awt.Dimension(54, 22));
        rbVenceuNao.setMinimumSize(new java.awt.Dimension(54, 22));
        rbVenceuNao.setPreferredSize(new java.awt.Dimension(54, 22));
        rbVenceuNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVenceuNaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVenceuLayout = new javax.swing.GroupLayout(jPanelVenceu);
        jPanelVenceu.setLayout(jPanelVenceuLayout);
        jPanelVenceuLayout.setHorizontalGroup(
            jPanelVenceuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVenceuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbVenceu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbVenceuSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbVenceuNao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanelVenceuLayout.setVerticalGroup(
            jPanelVenceuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVenceuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVenceuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbVenceuNao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbVenceuSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbVenceu))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanelPago.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPago.setMaximumSize(new java.awt.Dimension(190, 40));
        jPanelPago.setMinimumSize(new java.awt.Dimension(190, 40));
        jPanelPago.setPreferredSize(new java.awt.Dimension(190, 40));

        lbPago.setText("Pago:");

        grpPago.add(rbPagoSim);
        rbPagoSim.setText("Sim");
        rbPagoSim.setMaximumSize(new java.awt.Dimension(54, 22));
        rbPagoSim.setMinimumSize(new java.awt.Dimension(54, 22));
        rbPagoSim.setPreferredSize(new java.awt.Dimension(54, 22));
        rbPagoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPagoSimActionPerformed(evt);
            }
        });

        grpPago.add(rbPagoNao);
        rbPagoNao.setText("Não");
        rbPagoNao.setMaximumSize(new java.awt.Dimension(54, 22));
        rbPagoNao.setMinimumSize(new java.awt.Dimension(54, 22));
        rbPagoNao.setPreferredSize(new java.awt.Dimension(54, 22));
        rbPagoNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPagoNaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPagoLayout = new javax.swing.GroupLayout(jPanelPago);
        jPanelPago.setLayout(jPanelPagoLayout);
        jPanelPagoLayout.setHorizontalGroup(
            jPanelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPago)
                .addGap(18, 18, 18)
                .addComponent(rbPagoSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbPagoNao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanelPagoLayout.setVerticalGroup(
            jPanelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPagoNao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbPagoSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPago))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        lbIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/receber.png"))); // NOI18N

        jPanelDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lbFuncionario.setText("Funcionário:");

        lbCliente.setText("Cliente:");

        lbValorFinal.setText("Valor total:");

        lbFornecedor1.setText("null");

        lbFuncionario1.setText("null:");

        lbValorFinal1.setText("null");

        javax.swing.GroupLayout jPanelDescricaoLayout = new javax.swing.GroupLayout(jPanelDescricao);
        jPanelDescricao.setLayout(jPanelDescricaoLayout);
        jPanelDescricaoLayout.setHorizontalGroup(
            jPanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescricaoLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbFuncionario)
                    .addComponent(lbCliente)
                    .addComponent(lbValorFinal))
                .addGap(35, 35, 35)
                .addGroup(jPanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFornecedor1)
                    .addComponent(lbValorFinal1)
                    .addComponent(lbFuncionario1))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanelDescricaoLayout.setVerticalGroup(
            jPanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDescricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFornecedor1)
                    .addComponent(lbFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFuncionario1)
                    .addComponent(lbCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValorFinal1)
                    .addComponent(lbValorFinal))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbVencimento)
                    .addComponent(lbAReceber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(tfAReceber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbIcone)
                .addGap(28, 28, 28)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelVenceu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jPanelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanelVenceu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbIcone)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbAReceber)
                                    .addComponent(tfAReceber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbVencimento))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Confirmar.png"))); // NOI18N
        jbConfirmar.setText("CONFIRMAR");
        jbConfirmar.setPreferredSize(new java.awt.Dimension(132, 40));
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void tfAReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAReceberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAReceberActionPerformed

    private void tfVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVencimentoActionPerformed

    private void rbVenceuSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVenceuSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbVenceuSimActionPerformed

    private void rbVenceuNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVenceuNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbVenceuNaoActionPerformed

    private void rbPagoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPagoSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPagoSimActionPerformed

    private void rbPagoNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPagoNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPagoNaoActionPerformed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbConfirmarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grpPago;
    private javax.swing.ButtonGroup grpVencido;
    private javax.swing.JPanel jPanelDescricao;
    private javax.swing.JPanel jPanelPago;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelVenceu;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JLabel lbAReceber;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbFornecedor1;
    private javax.swing.JLabel lbFuncionario;
    private javax.swing.JLabel lbFuncionario1;
    private javax.swing.JLabel lbIcone;
    private javax.swing.JLabel lbPago;
    private javax.swing.JLabel lbValorFinal;
    private javax.swing.JLabel lbValorFinal1;
    private javax.swing.JLabel lbVenceu;
    private javax.swing.JLabel lbVencimento;
    private javax.swing.JRadioButton rbPagoNao;
    private javax.swing.JRadioButton rbPagoSim;
    private javax.swing.JRadioButton rbVenceuNao;
    private javax.swing.JRadioButton rbVenceuSim;
    private javax.swing.JFormattedTextField tfAReceber;
    private javax.swing.JFormattedTextField tfVencimento;
    // End of variables declaration//GEN-END:variables
}


